plugins {
    id 'java-library'
}

dependencies {
    // JSON Serialization
    api 'com.fasterxml.jackson.core:jackson-databind:2.18.0'
    api 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.18.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    // Test
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
